import { test, expect } from '@playwright/test';
import { TIMEOUT } from 'node:dns';
require('dotenv').config();
test('test', async ({ page }) => {

  await page.goto('https://ntuuat.service-now.com/login');
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill(process.env.USER_NAME);
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill(process.env.PASSWORD);
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.goto('https://ntuuat.service-now.com/nav_to.do?uri=%2Fhome.do%3F');
  await page.getByRole('button', { name: 'Nguyen Thi Quynh Trang User' }).click();
  await page.getByRole('menuitem', { name: 'Impersonate User' }).click();
  await page.getByRole('link', { name: 'Alison Le' }).click();
  
  await page.goto('https://ntuuat.service-now.com/esc');
  await page.getByRole('link', { name: 'Request Non-SSG CE Course' }).click();
  await page.getByLabel('Requester Details').locator('a').filter({ hasText: '-- None --' }).click();
  await page.getByRole('option', { name: 'New Course' }).click();
  await page.getByRole('textbox', { name: 'Name of Course' }).click();
  await page.getByRole('textbox', { name: 'Name of Course' }).fill('mba');
  await page.getByRole('link', { name: 'Lookup using list' }).click();
  await page.getByRole('option', { name: 'Academic Governance & Support' }).click();
  await page.getByLabel('Stakeholders', { exact: true }).locator('a').filter({ hasText: '-- None --' }).click();
  // await page.getByRole('option', { name: 'Partner Organisation only' }).click();
  // await page.locator('a').filter({ hasText: 'Partner Organisation only' }).click();
  await page.getByRole('option', { name: 'Partner and Client' }).click();
  await page.getByRole('combobox', { name: 'Required Programme Lead(s)' }).click();
  await page.getByRole('combobox', { name: 'Required Programme Lead(s)' }).fill('tét');
  await page.getByText('Tet Lin Edeline Mary Fong').click();
  await page.getByRole('textbox', { name: 'Stakeholders Remark' }).click();
  await page.getByRole('textbox', { name: 'Stakeholders Remark' }).fill('stakeholders remark');
  await page.getByRole('button', { name: 'Add a row for Partner' }).click();
  await page.getByRole('textbox', { name: 'Partner Name' }).click();
  await page.getByRole('textbox', { name: 'Partner Name' }).fill('test');
  await page.getByRole('textbox', { name: 'Partner Weblink' }).click();
  await page.getByRole('textbox', { name: 'Partner Weblink' }).fill('https://test.com');
  await page.locator('#s2id_sp_formfield_nsce_partner_type a').click();
  await page.getByRole('option', { name: '-- None --' }).click();
  await page.getByRole('textbox', { name: 'Partner Roles' }).click();
  await page.getByRole('textbox', { name: 'Partner Roles' }).fill('te');
  await page.getByRole('textbox', { name: 'Partner Roles' }).click();
  await page.getByRole('textbox', { name: 'Partner Roles' }).fill('test');
  await page.locator('#s2id_sp_formfield_nsce_industry_key_player a').click();
  await page.getByRole('option', { name: 'No', exact: true }).click();
  await page.locator('#s2id_sp_formfield_nsce_past_partnership_with_others a').click();
  // await page.getByRole('option', { name: '-- None --' }).click();
  // await page.locator('#s2id_sp_formfield_nsce_past_partnership_with_others a').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('#s2id_sp_formfield_nsce_industry_key_player a').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('textbox', { name: 'List of key educational' }).click();
  await page.getByRole('textbox', { name: 'List of key educational' }).fill('test');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('textbox', { name: 'Partner Organisation(s) Remark' }).click();
  await page.getByRole('textbox', { name: 'Partner Organisation(s) Remark' }).fill('partner orginisations remark');
  await page.getByRole('button', { name: 'Add a row for Client' }).click();
  await page.getByRole('textbox', { name: 'Client Name' }).click();
  await page.getByRole('textbox', { name: 'Client Name' }).fill('test');
  await page.getByRole('textbox', { name: 'Client Weblink' }).click();
  await page.getByRole('textbox', { name: 'Client Weblink' }).fill('https://test.com');
  await page.locator('#s2id_sp_formfield_nsce_client_type a').click();
  await page.getByRole('option', { name: 'Recurring' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('textbox', { name: 'Client Organisation(s) Remark' }).click();
  await page.getByRole('textbox', { name: 'Client Organisation(s) Remark' }).fill('client organisations remark');
  await page.getByRole('button', { name: 'Add a row for Trainer and' }).click();
  await page.getByRole('textbox', { name: 'Salutation/ Name' }).click();
  await page.getByRole('textbox', { name: 'Salutation/ Name' }).fill('est');
  await page.getByRole('textbox', { name: 'Salutation/ Name' }).click();
  await page.getByRole('dialog', { name: 'Trainer and Facilitators' }).dblclick();
  await page.getByRole('combobox', { name: 'Taught in this Course before?' }).fill('te');
  await page.locator('#s2id_autogen182_search').fill('test');
  await page.locator('#select2-drop-mask').click();
  await page.getByRole('textbox', { name: 'Relevant Qualifications/' }).fill('test');
  await page.locator('#s2id_sp_formfield_nsce_taught_in_this_course_before a').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('textbox', { name: 'Trainer and Facilitators' }).click();
  await page.getByRole('textbox', { name: 'Trainer and Facilitators' }).fill('trainer and facilitators remark');
  await page.getByRole('textbox', { name: 'Duration of Course (Hours)' }).click();
  await page.getByRole('textbox', { name: 'Duration of Course (Hours)' }).fill('12');
  await page.getByRole('textbox', { name: 'Duration of Course (Days)' }).dblclick();
  await page.getByRole('textbox', { name: 'Duration of Course (Days)' }).fill('1');
  await page.getByRole('textbox', { name: 'Projected Start Date' }).click();
  await page.getByRole('button', { name: 'Show Calendar for Projected' }).click();
  await page.getByRole('button', { name: 'Date picker is opened.01' }).click();
  await page.getByRole('textbox', { name: 'Projected Course Size' }).click();
  await page.getByRole('textbox', { name: 'Projected Course Size' }).fill('1');
  await page.locator('div').filter({ hasText: /^No\. of Courses planned over next 2 years$/ }).nth(2).click();
  await page.getByRole('textbox', { name: 'No. of Courses planned over' }).fill('1');
  await page.getByRole('textbox', { name: 'No. of Courses planned over' }).click();
  await page.locator('div:nth-child(5) > span > .row').click();
  await page.getByRole('combobox', { name: 'Required Age Range Help for' }).click();
  await page.getByRole('option', { name: '- 30 years' }).click();
  await page.getByRole('combobox', { name: 'Required Profession/ Academic' }).click();
  await page.getByRole('option', { name: 'University Students' }).click();
  await page.getByRole('textbox', { name: 'Organisation/ Institution' }).click();
  await page.getByRole('textbox', { name: 'Organisation/ Institution' }).fill('test');
  const page1Promise = page.waitForEvent('popup');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('paragraph').filter({ hasText: 'Complete and attach the Annex' }).nth(1).click();
  const page1 = await page1Promise;
  const download = await downloadPromise;
  await page.getByRole('textbox', { name: 'Course Fee ($)' }).click();
  await page.getByRole('textbox', { name: 'Course Fee ($)' }).fill('test');
  await page.getByRole('textbox', { name: 'Course Fee ($)' }).dblclick();
  await page.getByRole('textbox', { name: 'Course Fee ($)' }).fill('1');
  await page.getByRole('textbox', { name: 'Other Fees ($)' }).dblclick();
  await page.getByRole('textbox', { name: 'Other Fees ($)' }).fill('1');
  await page.getByText('Course Fee ($)EOM ($)OOE ($)').click();
  await page.getByText('Course Fee ($)EOM ($)OOE ($)').click();
  await page.getByRole('textbox', { name: 'EOM ($)' }).click();
  await page.getByRole('textbox', { name: 'EOM ($)' }).fill('1');
  await page.getByRole('textbox', { name: 'Overhead Costs ($)' }).click();
  await page.getByRole('textbox', { name: 'Overhead Costs ($)' }).fill('1');
  await page.getByRole('textbox', { name: 'OOE ($)' }).click();
  await page.getByRole('textbox', { name: 'OOE ($)' }).fill('1');
  await page.getByRole('textbox', { name: 'Class Size (Pax)' }).click();
  await page.getByRole('textbox', { name: 'Class Size (Pax)' }).fill('1');
  await page.getByRole('textbox', { name: 'Total Expenditures' }).click();
  await page.getByRole('textbox', { name: 'Financial Projection Remark' }).click();
  await page.getByRole('textbox', { name: 'Financial Projection Remark' }).fill('financial projection remark');
  await page.getByText('Annex A One page CV for each Trainer(s) and Facilitator(s)', { exact: true }).click();
  await page.locator('#nsce_commit_annex_a_document div').filter({ hasText: /^Annex A One page CV for each Trainer\(s\) and Facilitator\(s\)$/ }).click();
  await page.locator('#nsce_commit_annex_b_course_info div').filter({ hasText: /^Annex B Course Information$/ }).dblclick();
  await page.getByText('Annex A One page CV for each Trainer(s) and Facilitator(s)', { exact: true }).click();
  await page.getByText('Annex B Course Information', { exact: true }).click();
  await page.getByText('Curriculum for Course').click();
  await page.getByText('Add attachments').click();
  await page.getByRole('button', { name: 'Choose a file' }).click();
  await page.getByRole('button', { name: 'Choose a file' }).setInputFiles('Annex A Trainer(s) and Facilitator(s) (2).docx');
  await page.getByRole('button', { name: 'Submit', exact: true }).click();
  await page.getByRole('combobox', { name: 'Required Country of Origin' }).click();
  await page.getByRole('option', { name: 'Albania' }).click();
  await page.locator('ul').filter({ hasText: 'Albania' }).click();
  await page.getByRole('option', { name: 'Andorra' }).click();
  await page.getByRole('button', { name: 'Submit', exact: true }).click();
  await page.getByRole('menuitem', { name: 'User options: Alison Le' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await page.goto('https://loginfs.ntu.edu.sg/adfs/ls/?SAMLRequest=lVJNT%2BswEPwrke9xPuin1VQqrRCVeLyIFg7cXHtdLDl2ntcu8O9fmhYBBypx9c7szM54hrwxZcsWMbzYB%2FgXAUPy1hiL7DSpSPSWOY4ameUNIAuCbRZ%2F7lhJc9Z6F5xwhiQLRPBBO7t0FmMDfgP%2BoAU8PtxV5CWEFlmW2RAjDxRPo9S6Vypck1l%2BaPkeqHQkWXUGtOXHTZ884%2FbaKqQdn4KMFPcZlwozgxlJbpwX0PuvSPARSLJeVWRzv5xMJ8MyH0zz0Wg8FlJdDRWUaqeUGE4ncrDrgFhzRH2Aiihu8EhFjLC2GLgNFSnzcpTmgzQvtvmEFWM2KGg%2BGj6TpD4ffq2t1HZ%2FOaXdCYTsdrut0%2FrvZtsvOGgJ%2Fr5D%2FyqgJ%2FDYh9NtJvNZ3xLrbfuvxV12xD%2FaIvPL0rPsq8BZrmVH1%2BtV7YwW78nCGPe69MADfDTQddLw8LOHghb9i5ap6qEsWmxBaKVBkmx%2Blv3%2BL%2Bf%2FAQ%3D%3D&RelayState=https%3A%2F%2Fntuuat.service-now.com%2Fesc');
});